sdkversion: "3.4.0"
name: "InventoryManagement"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "4.6"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator5.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.inventorymanagement"
  BundleURLScheme: "inventorymanagement"
wp:
  productid: "25b37be0-018e-0130-1560-1094e40a804e"
symbian:
  uid: "0xea9d0d4b"
android:
  version: "2.1"
extensions:
  - json
  - another-extension
app_type: "rhoelements"
capabilities:
  - non_motorola_device
